const skills = {
  StripBall: 1,
  IncreaseStrength: 2,
  IncreaseAgility: 3,
  IncreaseMovement: 4,
  IncreaseArmour: 5,
  Catch: 6,
  Dodge: 7,
  Sprint: 8,
  PassBlock: 9,
  FoulAppearance: 10,
  Leap: 11,
  ExtraArms: 12,
  MightyBlow: 13,
  Leader: 14,
  Horns: 15,
  TwoHeads: 16,
  StandFirm: 17,
  AlwaysHungry: 18,
  Regeneration: 19,
  TakeRoot: 20,
  Accurate: 21,
  BreakTackle: 22,
  SneakyGit: 23,
  Chainsaw: 25,
  Dauntless: 26,
  DirtyPlayer: 27,
  DivingCatch: 28,
  DumpOff: 29,
  Block: 30,
  BoneHead: 31,
  VeryLongLegs: 32,
  DisturbingPresence: 33,
  DivingTackle: 34,
  Fend: 35,
  Frenzy: 36,
  Grab: 37,
  Guard: 38,
  HailMaryPass: 39,
  Juggernaut: 40,
  JumpUp: 41,
  Loner: 44,
  NervesOfSteel: 45,
  NoHands: 46,
  Pass: 47,
  PilingOn: 48,
  PrehensileTail: 49,
  Pro: 50,
  ReallyStupid: 51,
  RightStuff: 52,
  SafeThrow: 53,
  SecretWeapon: 54,
  Shadowing: 55,
  SideStep: 56,
  Tackle: 57,
  StrongArm: 58,
  Stunty: 59,
  SureFeet: 60,
  SureHands: 61,
  ThickSkull: 63,
  ThrowTeamMate: 64,
  Unknown_65: 65, // ??
  WildAnimal: 67,
  Wrestle: 68,
  Tentacles: 69,
  MultipleBlock: 70,
  Kick: 71,
  KickOffReturn: 72,
  BigHand: 74,
  Claw: 75,
  BallChain: 76,
  Stab: 77,
  HypnoticGaze: 78,
  Stakes: 79,
  Bombardier: 80,
  Decay: 81,
  NurglesRot: 82,
  Titchy: 83,
  BloodLust: 84,
  FanFavourite: 85,
  Animosity: 86
};

const skillNames = {
  [skills.StripBall]: "Strip Ball",
  [skills.IncreaseStrength]: "ST+",
  [skills.IncreaseAgility]: "AG+",
  [skills.IncreaseMovement]: "MA+",
  [skills.IncreaseArmour]: "AV+",
  [skills.Catch]: "Catch",
  [skills.Dodge]: "Dodge",
  [skills.Sprint]: "Sprint",
  [skills.PassBlock]: "Pass Block",
  [skills.FoulAppearance]: "Foul Appearance",
  [skills.Leap]: "Leap",
  [skills.ExtraArms]: "Extra Arms",
  [skills.MightyBlow]: "Mighty Blow",
  [skills.Leader]: "Leader",
  [skills.Horns]: "Horns",
  [skills.TwoHeads]: "Two-Heads",
  [skills.StandFirm]: "Stand Firm",
  [skills.AlwaysHungry]: "Always Hungry",
  [skills.Regeneration]: "Regeneration",
  [skills.TakeRoot]: "Take Root",
  [skills.Accurate]: "Accurate",
  [skills.BreakTackle]: "Break Tackle",
  [skills.SneakyGit]: "Sneaky Git",
  [skills.Chainsaw]: "Chainsaw",
  [skills.Dauntless]: "Dauntless",
  [skills.DirtyPlayer]: "Dirty Player",
  [skills.DivingCatch]: "Diving Catch",
  [skills.DumpOff]: "Dump-Off",
  [skills.Block]: "Block",
  [skills.BoneHead]: "Bone-Head",
  [skills.VeryLongLegs]: "Very Long Legs",
  [skills.DisturbingPresence]: "Disturbing Presence",
  [skills.DivingTackle]: "Diving Tackle",
  [skills.Fend]: "Fend",
  [skills.Frenzy]: "Frenzy",
  [skills.Grab]: "Grab",
  [skills.Guard]: "Guard",
  [skills.HailMaryPass]: "Hail-Mary Pass",
  [skills.Juggernaut]: "Juggernaut",
  [skills.JumpUp]: "Jump-Up",
  [skills.Loner]: "Loner",
  [skills.NervesOfSteel]: "Nerves Of Steel",
  [skills.NoHands]: "No Hands",
  [skills.Pass]: "Pass",
  [skills.PilingOn]: "Piling On",
  [skills.PrehensileTail]: "Prehensile Tail",
  [skills.Pro]: "Pro",
  [skills.ReallyStupid]: "Really Stupid",
  [skills.RightStuff]: "Right Stuff",
  [skills.SafeThrow]: "Safe Throw",
  [skills.SecretWeapon]: "Secret Weapon",
  [skills.Shadowing]: "Shadowing",
  [skills.SideStep]: "Side Step",
  [skills.Tackle]: "Tackle",
  [skills.StrongArm]: "Strong Arm",
  [skills.Stunty]: "Stunty",
  [skills.SureFeet]: "Sure Feet",
  [skills.SureHands]: "Sure Hands",
  [skills.ThickSkull]: "Thick Skull",
  [skills.ThrowTeamMate]: "Throw Team Mate",
  [skills.WildAnimal]: "Wild Animal",
  [skills.Wrestle]: "Wrestle",
  [skills.Tentacles]: "Tentacles",
  [skills.MultipleBlock]: "Multiple Block",
  [skills.Kick]: "Kick",
  [skills.KickOffReturn]: "Kick-Off Return",
  [skills.BigHand]: "Big Hand",
  [skills.Claw]: "Claw",
  [skills.BallChain]: "Ball and Chain",
  [skills.Stab]: "Stab",
  [skills.HypnoticGaze]: "Hypnotic Gaze",
  [skills.Stakes]: "Stakes",
  [skills.Bombardier]: "Bombardier",
  [skills.Decay]: "Decay",
  [skills.NurglesRot]: "Nurgles Rot",
  [skills.Titchy]: "Titchy",
  [skills.BloodLust]: "Blood-Lust",
  [skills.FanFavourite]: "Fan Favourite",
  [skills.Animosity]: "Animosity"
};
